# 235
mongo_235:
    host: '114.80.150.196'
    port: 27777
    user_name: 'goojia'
    password: 'goojia7102'
    db_name: deal_price
    coll_comm: lianjiazaixian

# online
mongo:
    host: '192.168.0.43'
    port: 27017
    db_name: fangjia
    coll_comm: deal_price
    user_name:
    password:

#235
rabbit:
    host: '114.80.150.196'
    port: 5673
    user_name:
    password:

# local
#rabbit:
#    host: 'localhost'
#    port: 5673
#    user_name:
#    password:

