mongo_235:
    host: '114.80.150.196'
    port: 27777
    user_name: 'goojia'
    password: 'goojia7102'
    db_name: deal_price
    collection: wangyi

mongo_136:
    host: '192.168.0.136'
    port: 27017
    db_name: fangjia_base
    collection: sale_data_stat


rabbit:
    host: '114.80.150.196'
    port: 5673
    user_name:
    password: