mongo_235:
    host: '114.80.150.196'
    port: 27777
    user_name: 'goojia'
    password: 'goojia7102'
    db_name: deal_price
    collection: youda_deal_price_2018_11
    match_db: friends
    collection_youda_res_xzj: xzj_yd_res_fj


