# local
mongo:
    host: localhost
    port: 27017
    db_name : fangjia_youfang
    coll_comm : news_library_1
    url_code : article_id
    comments : comments
mongo_config:
    config_host: 114.80.150.196
    port: 27777
    user_name: goojia
    password: goojia7102
    config_db : article
    coll_detail : detail_config
    coll_list : list_config
    clean : clean
rabbitmq_host : localhost
rabbitmq_port : 5673
redies_host : localhost
redis_port : 6379
redis_db : 0

# online
#mongo:
#    host: 192.168.0.43
#    port: 27017
#    db_name : fangjia_youfang
#    coll_comm : news_library_1
#    url_code : article_id
#    comments : comments
#mongo_config:
#    config_host: 114.80.150.196
#    port: 27777
#    user_name: goojia
#    password: goojia7102
#    config_db : article
#    coll_detail : detail_config
#    coll_list : list_config
#    clean : clean
#rabbitmq_host : localhost
#rabbitmq_port : 5673
#redies_host : localhost
#redis_port : 6379
#redis_db : 0
