# to true
mongo:
    host: 114.80.150.196
    port: 27777
    user_name: 'goojia'
    password: 'goojia7102'
    db: auction
    collection: auction_latest

rabbit:
    host: localhost
    port: 5673


# online
#mongo:
#    host: 114.80.150.196
#    port: 27777
#    user_name: 'fangjia'
#    password: 'fangjia123456'
#    db: auction
#    collection: auction_all_type

