# to true
mongo:
  host: '114.80.150.196'
  port: 27777
  user_name: 'goojia'
  password: 'goojia7102'
  db: company
  collection: office_building
#  collection: company_baidumap_update
#  collection: company_crawler
rabbitmq:
  host: '114.80.150.196'
#  host: 'localhost'
  port: 5673
source_config:
  host: 114.80.150.196
  port: 3336
  user_name: root
  password: goojia7102
  db_name: company_config


param:
  city: '城市'
  address: '公司地址'
  company_name: '公司名称'
  region: '区域'
  company_short_info: '公司简介'
  company_info: '公司介绍'
  business: '公司行业'
  company_size: '公司规模/人数'
  development_stage: '发展阶段'
  registration_time: '注册时间'
  registered_capital: '注册资本'
  operating_period: '经营期限'
  company_source: '信息来源'
  company_id: '公司id'
  url: '公司链接'
  fj_city: '格式化城市'
  fj_region: '格式化区域'
